name: Node.js + MySQL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: StrongPassword123!
          MYSQL_DATABASE: three_tier_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pStrongPassword123!" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code (ESLint)
        run: npx eslint .

      - name: Wait for MySQL to be ready
        run: |
          echo "⏳ Waiting for MySQL to be ready..."
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -uroot -pStrongPassword123! --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Test DB connection
        run: |
          node -e "const mysql=require('mysql2');const c=mysql.createConnection({host:'127.0.0.1',user:'root',password:'StrongPassword123!',database:'three_tier_db'});c.connect(e=>{if(e){console.error('❌ DB Connection Failed:',e.message);process.exit(1);}console.log('✅ DB Connection Success');c.end();});"

      - name: Run tests
        run: npm test || echo "No tests defined"
